### ISSUE TITLE
Back to main menu when dismiss

### ISSUE THREAD

**Issue by aztecrabbit** [AndroidPoet/Dropdown#7]
I access the sub-menu, close it, and if I open the menu again, the previous sub-menu appears. I don't want it to be like that. How can I return to the main menu when I dismiss the sub-menu?

**Comment by AndroidPoet** [comment]
Thank you for reporting this issue @aztecrabbit ,identified the problem with sub-menu persistence and it will be fixed in the next update.

**Comment by aztecrabbit** [comment]
Thank you!

**Comment by aztecrabbit** [comment]
Hi, it is possible to release this fixed version to maven?

**Comment by AndroidPoet** [comment]
Hi @aztecrabbit,Maven recently implemented some changes, and I am currently encountering issues with publishing the latest version. I will publish it as soon as these issues are resolved.

**Comment by AndroidPoet** [comment]
Hi @aztecrabbit, the issues have been fixed and will be available in version 1.1.3. Thank you for supporting my work! You are my first sponsor on GitHub, and it means a lot to me.
