### ISSUE TITLE
MenuItemText font size too small and vertical alignment is broken

### ISSUE THREAD

**Issue by aztecrabbit** [AndroidPoet/Dropdown#9]
**Please complete the following information:**
- Library Version: `v1.1.3`
- Affected Device(s): `sdk_gphone_x86_64 Android 14`, `POCO F6 Android 14`
 
**Describe the Bug:**

The MenuItemText font size is too small, and the vertical alignment does not match the baseline

**sdk_gphone_x86_64 Android 14**

![2024-09-06-165653_541x851_scrot](https://github.com/user-attachments/assets/a57fe077-87ce-4242-9712-5bdb8bb53785)

**POCO F6 Android 14**

![2024-09-06-170406_734x1158_scrot](https://github.com/user-attachments/assets/5d2a7cd8-5fae-4656-8628-f8080624d3b9)

I think because of this, [code](https://github.com/AndroidPoet/Dropdown/blob/dbe252e8cd74352f0bc6a2bb612086ea8479e800/dropdown/src/commonMain/kotlin/io/androidpoet/dropdown/DropDown.kt#L214-L219)

```kotlin
val style =
  if (isHeaderText) {
    MaterialTheme.typography.bodyMedium
  } else {
    MaterialTheme.typography.bodySmall
  }
```

And the previous version is using this code, i believe

```kotlin
val style =
  if (isHeaderText) {
    MaterialTheme.typography.subtitle2
  } else {
    MaterialTheme.typography.subtitle1
  }
```

**Expected Behavior:**

Like in the previous version `v1.1.2`, using `subtitle2` and `subtitle1`, the font size looks very good when seeing it directly to the android device.

**Comment by AndroidPoet** [comment]
fixed
